"""empty message

Revision ID: ce79d19a0018
Revises: 420e54da6389
Create Date: 2018-04-30 01:04:53.120571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce79d19a0018'
down_revision = '420e54da6389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('auth', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'auth')
    # ### end Alembic commands ###
